const cartItems = [
  {
    id: 1,
    // name: "Premium Leather Backpack",
    name: "rack",
    description: "Brown / Large",
    price: 129.99,
    quantity: 1,
    image:
      "https://img.drz.lazcdn.com/static/np/p/0bf911dcf19a636a100867aab89e632d.jpg_720x720q80.jpg",
  },
  {
    id: 2,
    // name: "Wireless Earbuds Pro",
    name: "rack",
    description: "White",
    price: 199.99,
    quantity: 1,
    image:
      "https://static-01.daraz.com.np/p/8c922f8728a32ec3f0b573281f413ede.png",
  },
  {
    id: 3,
    // name: "Smart Watch Series 5",
    name: "rack",
    description: "Space Gray / 44mm",
    price: 299.99,
    quantity: 1,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ77Ub_H4ZgSXTqxR7bMbFxrHvJ4nJXCqpBgQ&s",
  },
  {
    id: 4,
    // name: "Gaming Mechanical Keyboard",
    name: "rack",
    description: "RGB Backlit / Blue Switch",
    price: 89.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/71rG-IUz9VL._AC_SL1500_.jpg",
  },
  {
    id: 5,
    // name: "4K Ultra HD Monitor",
    name: "rack",
    description: "27-inch / 144Hz",
    price: 399.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/81KZcn2y6GL._AC_SL1500_.jpg",
  },
  {
    id: 6,
    // name: "Noise Cancelling Headphones",
    name: "rack",
    description: "Black / Over-ear",
    price: 249.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/61jli29r7oL._AC_SL1500_.jpg",
  },
  {
    id: 7,
    // name: "Portable Bluetooth Speaker",
    name: "rack",
    description: "Waterproof / Blue",
    price: 59.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/81-Y6N7HQCL._AC_SL1500_.jpg",
  },
  {
    id: 8,
    // name: "Wireless Charging Pad",
    name: "rack",
    description: "Fast Charge / 10W",
    price: 29.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/61MaH6xMJvL._AC_SL1500_.jpg",
  },
  {
    id: 9,
    // name: "Ergonomic Office Chair",
    name: "rack",
    description: "Black Mesh / Adjustable",
    price: 179.99,
    quantity: 1,
    image: "https://m.media-amazon.com/images/I/71R4bnTOeDL._AC_SL1500_.jpg",
  },
  {
    id: 10,
    name: "Laptop Stand ",
    description: "Aluminum / Adjustable Height",
    price: 49.99,
    quantity: 1,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCX9kZwkd_UXRc6kpVYN6AA0eI_U90gEfLaQ&s",
  },
];

export default cartItems;
